[package]
name = "slang-native-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.6"
pollster = "0.4.0"
wgpu = { version = "24.0.1", features = ["serde"] }
winit = "0.30.9"
bytemuck = "1.21.0"
reqwest = { version = "0.12.12", features = ["blocking"] }
image = "0.25.5"
rand = "0.9.0"
url = "2.5.4"
futures-channel = "0.3.31"
tokio = "1.43.0"
egui-winit = "0.31.0"
egui-wgpu = "0.31.0"
egui = "0.31.0"
regex = "1.11.1"
serde = { version = "1.0.217", features = ["derive"] }
ron = "0.8.1"

[build-dependencies]
slang = { git = "https://github.com/Devon7925/slang-rs.git" }
strum = "0.27"
strum_macros = "0.27"
regex = "1.11.1"
wgpu = { version = "24.0.1", features = ["serde"] }
serde = { version = "1.0.217", features = ["derive"] }
ron = "0.8.1"
